version: '2'
services:
    conoche-app:
        image: conoche
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://conoche-mysql:3306/conoche?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    conoche-mysql:
        extends:
            file: mysql.yml
            service: conoche-mysql
